sudo: required
language: scala
scala:
  - 2.12.2
jdk:
  - oraclejdk8
script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.4.0/0.4.0-9-1db2ee && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
  - mill __.clean && mill __.test && mill __.scoverage.xmlReport 
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/bin/mill"
before_install:
  - pip install --user codecov
  - sudo chmod +x /usr/local/bin/sbt
after_success:
- codecov
- test "$TRAVIS_REPO_SLUG" == 'fulcrumgenomics/commons' && test "$TRAVIS_PULL_REQUEST"
  == 'false' && test "$TRAVIS_BRANCH" == 'master' && mill mill.scalalib.PublishModule/publishAll "${SONATYPE_USERNAME}:${SONATYPE_PASSWORD}" __.publishArtifacts --release true
env:
  global:
  - secure: erKEtyVxyTgRQIrzva785xST9EhsYY+40SKhaHumIvXgfHtL6SppXCd213LXdwrKms23v/BZ43I5gOfEuX405FV1a8B7e+IGj1sG118MtlcVEyqSfuwGWtmsjhyWkvfHdyXzC8Aej5FpT9il74IdYJYVWW18UOh/q7cBI3duV5p9iooJG6IZ8zc1042+uKq4sfM9EnZEyCiffpVmqknRWZ47vlDEOiURYqccvJ0VN2P2mWSHTRMlXPGHuhy5KVMC/DIsZFbX2MaKMIT73hGMA8l6RS98ZSk7DkgrNr3hKy7P4YU9VyLRiz7S4MhCmS2L/NUEGI6V5Gouxpol+IX93IcpLp0ZgzYMfpnWfZyjTIx627cKKAsSOqoGteRFRArKwbag15u9lHltAu911PVa2bICZy0snr/CQx18++3hIPrKXLk5MnU4jQGOtZ1FbScPgEJBP2M6bUKHKPx2EJfQ5KtJgQtpv26LwLhrlJ+lRRQrirL0N3PAcciRtjGubAlB4ai9Qx6dVdJ84tlWMcgvZA2HExnK8uU6MK1biWBZevMrJ8qeb55CCaK5R7fZZJvAYKH9LIxt2YO2C8tVDEmPxjiZBp6jr9Ib+oiHU27PhUxzG1xK264tzp1LoBIewcUunbicDzqBPsQ60ByCaBhgin76E6+H+uxUY3tEnuIWX7c=
  - secure: d49CI/KESi2p2JhYDKVoWHtaPzN+E6sMrbBob6Wm4rGwbdxka20buK/LclKWV9Kvnles6BUoDTw2dj/yKLCgpomqCjpF/3wyjS7JT0qKzd2v5rfxc3YbRqvyWbceeNdqbRTlHMIK00ltLIPLVL33GftF4t8lZFQ2Y6SZpO6iPWoecLT0lx5oSNtu3puDo1aDn9XnGABVQu4UkAAObC0YUH0BRKny802xM5NIgQwWBti/34nLfNZ7DveR9K1iZRiSbMFdwj21xDqBsV8zohSmKG7WUvctBUhBufvIg9Tlv4XtCYUB1hUhBTY33lfRX0C0o6nM1ZAHN5nXz9Nqt+Xww3CILff9ldKeCKB6CM7GHiN5uovCQ6W7n1KlJfx80bfsMWD2FWi3xPq95j7L/blfiAgl9FnvgtZYmKpEXgJka6ldrxaQMiujXxK9LpquSlm5BAFO2Y/za5Pr+6aTtdjO2POC3TNQi0rf0dLNHAVqjbBcWSyT5zox3WLC7D7qV13NUTujTQ4f9Y0FUPijhb8wZ43++x4O9tIhG9sQsx+YehwMPUwaYSFgsOXat8tTCMBj4fVhWOu+cVHZ+sMVI2Jm1YzResHOOmKJzOqw/DBaT5JpuBDmHOPqikCNbqkWuJooz3YrVXP/zhddR/fBZjApCkmNFgfkfcQmtsnc+ohRUYs=
